'use strict';

// ── Prompt categories ─────────────────────────────────────────────────────────
//
// Each category has an id, a display label, an emoji, and an array of prompts.
// The server picks one prompt at random from the chosen category each round.
// Passing category 'all' picks from every prompt across all categories.
//
const CATEGORIES = [
  {
    id:     'all',
    label:  'All Categories',
    emoji:  '🎲',
  },
  {
    id:     'food',
    label:  'Food & Drink',
    emoji:  '🍕',
    prompts: [
      'Name a fruit',
      'Name a vegetable',
      'Name a citrus fruit',
      'Name a berry',
      'Name a tropical fruit',
      'Name a fast food restaurant',
      'Name a pizza topping',
      'Name a breakfast food',
      'Name a snack food',
      'Name a type of pasta',
      'Name a sandwich filling',
      'Name a salad ingredient',
      'Name a dessert',
      'Name an ice cream flavour',
      'Name a type of cake',
      'Name a fizzy drink',
      'Name a hot drink',
      'Name a type of cheese',
      'Name something you put on toast',
      'Name a condiment',
      'Name a type of cuisine',
      'Name a spice or herb',
      'Name something you find in a sushi restaurant',
      'Name a BBQ food',
      'Name a food that is orange',
      'Name a food that is green',
      'Name a food you eat with your hands',
      'Name a soup',
      'Name something you dip chips in',
      'Name a food that comes in a tin',
      'Name a type of bread',
      'Name a pasta sauce',
      'Name a cocktail',
      'Name something you eat at a cinema',
      'Name a type of biscuit or cookie',
      'Name a food you put in a salad',
      'Name a street food',
      'Name something you put on a hot dog',
      'Name a food that is yellow',
      'Name a food that goes with peanut butter',
      'Name something you might have for lunch',
      'Name a type of noodle dish',
      'Name a food that has cheese in it',
      'Name a famous chocolate bar',
      'Name a breakfast cereal',
      'Name a food that is crunchy',
      'Name a food that is soft',
      'Name something found in a Mexican dish',
      'Name a popular takeaway food',
      'Name something you season food with',
    ],
  },
  {
    id:     'nature',
    label:  'Nature & Science',
    emoji:  '🌍',
    prompts: [
      'Name a country in Europe',
      'Name a country in Asia',
      'Name a country in South America',
      'Name an ocean',
      'Name a type of weather',
      'Name an animal that lives in the ocean',
      'Name a jungle animal',
      'Name a farm animal',
      'Name a bird',
      'Name an insect',
      'Name something you find in a forest',
      'Name a type of tree',
      'Name a flower',
      'Name a planet in our solar system',
      'Name a type of rock or gemstone',
      'Name a natural disaster',
      'Name something you see in the sky at night',
      'Name a continent',
      'Name a famous mountain',
      'Name a type of cloud',
      'Name a season',
      'Name something you find at the bottom of the sea',
      'Name a reptile',
      'Name a type of fish',
      'Name a nocturnal animal',
      'Name an endangered animal',
      'Name a dog breed',
      'Name a cat breed',
      'Name a type of bear',
      'Name a large cat',
      'Name an animal with a long neck',
      'Name an animal with a shell',
      'Name a type of shark',
      'Name a small insect',
      'Name a type of snake',
      'Name a famous river',
      'Name a famous desert',
      'Name a type of forest',
      'Name something a plant needs to grow',
      'Name a type of storm',
      'Name a thing you find on a beach',
      'Name an animal that hibernates',
      'Name a primate',
      'Name a marsupial',
      'Name a type of whale',
      'Name something that lives underground',
      'Name a famous astronaut',
      'Name something found in space',
      'Name something you might see on a nature walk',
      'Name an animal that migrates',
    ],
  },
  {
    id:     'entertainment',
    label:  'Entertainment',
    emoji:  '🎬',
    prompts: [
      'Name a movie genre',
      'Name a TV show everyone has seen',
      'Name a streaming service',
      'Name a Disney movie',
      'Name a Pixar movie',
      'Name a superhero',
      'Name a Marvel character',
      'Name a DC character',
      'Name a famous villain',
      'Name a cartoon character',
      'Name a type of dance',
      'Name a musical instrument',
      'Name a type of music',
      'Name a genre of book',
      'Name a famous fictional robot',
      'Name a decade known for its music',
      'Name a famous children\'s TV character',
      'Name a type of video game',
      'Name a famous movie franchise',
      'Name a romantic movie',
      'Name a horror movie monster',
      'Name a famous TV detective',
      'Name a film set in space',
      'Name a famous animated villain',
      'Name a reality TV show',
      'Name a talent competition show',
      'Name a crime drama series',
      'Name a sitcom from the 90s',
      'Name a famous movie director',
      'Name a famous fictional wizard',
      'Name a classic fairy tale',
      'Name a famous fictional animal',
      'Name a famous fictional spy',
      'Name something a DJ uses',
      'Name a music festival',
      'Name a type of concert venue',
      'Name a famous musical',
      'Name a fictional universe from a movie',
      'Name a famous animated TV show',
      'Name a famous TV game show',
      'Name a classic video game character',
      'Name a war movie',
      'Name a comedy film',
      'Name a famous movie sequel',
      'Name a famous movie based on a book',
      'Name a film with a number in the title',
      'Name a popular Netflix series',
      'Name a type of documentary',
      'Name a famous anime series',
      'Name something you find at a film premiere',
    ],
  },
  {
    id:     'sports',
    label:  'Sports & Games',
    emoji:  '⚽',
    prompts: [
      'Name a sport',
      'Name an Olympic sport',
      'Name a sport played with a ball',
      'Name a water sport',
      'Name a winter sport',
      'Name a combat sport',
      'Name a racket sport',
      'Name a board game',
      'Name a card game',
      'Name a video game console',
      'Name a famous football club',
      'Name a famous sports brand',
      'Name a famous athlete',
      'Name a team sport',
      'Name an individual sport',
      'Name something you find in a gym',
      'Name a piece of sports equipment',
      'Name a famous golfer',
      'Name a famous football manager',
      'Name a famous tennis tournament',
      'Name something a referee does',
      'Name a famous sports stadium',
      'Name a sport with a net',
      'Name a sport where you need a helmet',
      'Name something you do to warm up',
      'Name a famous Formula 1 driver',
      'Name a type of race',
      'Name a sport played on a court',
      'Name a sport played on ice',
      'Name something you find in a swimming pool',
      'Name a position in football',
      'Name a famous boxer',
      'Name a piece of gymnastics equipment',
      'Name a sport where you use a stick',
      'Name a chess piece',
      'Name a card game for two players',
      'Name a playground game',
      'Name a party game',
      'Name a game with dice',
      'Name something you need for camping and hiking',
      'Name a type of yoga pose',
      'Name a street sport',
      'Name a sport with a goal',
      'Name a sport where you score points with a ball',
      'Name something in a sports changing room',
      'Name a famous sporting event',
      'Name a dangerous sport',
      'Name a sport with a bat',
      'Name a sport you can do alone',
      'Name something fans do at a sports match',
    ],
  },
  {
    id:     'everyday',
    label:  'Everyday Life',
    emoji:  '🏠',
    prompts: [
      'Name something you bring to the beach',
      'Name something you find in a kitchen',
      'Name something in a backpack',
      'Name something you find in a bathroom',
      'Name something you find in a bedroom',
      'Name something you find in an office',
      'Name something in a first aid kit',
      'Name something you find at a petrol station',
      'Name something you do on a Sunday morning',
      'Name something you do before bed',
      'Name something you do in the morning',
      'Name a chore people hate doing',
      'Name something you take on a flight',
      'Name something you keep in your wallet',
      'Name something you buy at a supermarket every week',
      'Name a reason someone might be late',
      'Name something people do when they\'re bored',
      'Name a sound you hear in a city',
      'Name something you do when you\'re sick',
      'Name a thing people collect as a hobby',
      'Name something you find in a junk drawer',
      'Name a type of bag',
      'Name something that comes in a box',
      'Name something you throw away every day',
      'Name a reason to call in sick',
      'Name something you do on a rainy day',
      'Name a household appliance',
      'Name something in a living room',
      'Name a tool you find in a garage',
      'Name something you do on a long car journey',
      'Name a reason people go to the doctor',
      'Name a type of shop',
      'Name something people argue about at home',
      'Name something that always goes missing',
      'Name something kids don\'t want to do',
      'Name a reason to stay home from school',
      'Name something you do on a Friday night',
      'Name something you forget to pack when travelling',
      'Name something you leave in your car',
      'Name a habit people try to break',
      'Name an app people use every day',
      'Name a thing you check on your phone first thing',
      'Name something you need for a road trip',
      'Name something that breaks easily',
      'Name something everyone owns but rarely uses',
      'Name a thing you do when you get home from work',
      'Name a reason to do laundry immediately',
      'Name something you do before leaving the house',
      'Name something you find on a desk',
      'Name a reason someone might move house',
    ],
  },
  {
    id:     'spicy',
    label:  'Spicy',
    emoji:  '🌶️',
    prompts: [
      'Name a reason to text your ex',
      'Name a red flag on a first date',
      'Name a reason to delete your browser history',
      'Name a place people go on a first date',
      'Name an app people use to meet someone',
      'Name something people lie about on a dating app',
      'Name a sign someone is flirting with you',
      'Name a reason someone might stay overnight',
      'Name something that kills the mood',
      'Name a reason to cancel plans at the last minute',
      'Name something you notice first about someone attractive',
      'Name a bad excuse for being late',
      'Name something you hide under your bed',
      'Name a reason to leave a party early',
      'Name something you do in the shower besides washing',
      'Name something embarrassing to be caught buying',
      'Name a reason to turn the lights off',
      'Name something you change about yourself before a date',
      'Name a body language sign that someone likes you',
      'Name a sign a date is going badly',
      'Name a sign a date is going well',
      'Name a type of date night',
      'Name a reason two people might share a bed',
      'Name something you pretend to be asleep for',
      'Name an excuse to cancel a date',
      'Name something people do after a break-up',
      'Name a reason to sneak out',
      'Name a reason to ghost someone',
      'Name a deal-breaker in a relationship',
      'Name something adults do that they blame on being tired',
      'Name a reason to close a tab quickly',
      'Name a type of person you probably shouldn\'t date',
      'Name something you check about someone before a first date',
      'Name a reason couples argue',
      'Name a sign someone is bad at texting back',
      'Name something you shouldn\'t do in front of a new partner',
      'Name something people do to make someone jealous',
      'Name something you check on a crush\'s social media',
      'Name a reason to fake being sick',
      'Name a compliment people give when they\'re flirting',
      'Name a reason someone might arrive home very late',
      'Name something that makes a bad first impression',
      'Name something people lie about online',
      'Name something a bad roommate does',
      'Name a reason to regret a night out',
      'Name something you quickly hide when someone walks in',
      'Name a reason to sneak back into the house',
      'Name something people lie about in a relationship',
      'Name something people do at a sleepover',
      'Name a reason couples break up',
    ],
  },
  {
    id:     'random',
    label:  'Random & Fun',
    emoji:  '✨',
    prompts: [
      'Name something that is always cold',
      'Name something that is always hot',
      'Name something that makes a loud noise',
      'Name something red',
      'Name something round',
      'Name something that can fly',
      'Name something you do when you\'re nervous',
      'Name something you do when you\'re happy',
      'Name a word that rhymes with "cat"',
      'Name a word that rhymes with "night"',
      'Name something that gets better with age',
      'Name something you should never do on a first date',
      'Name a bad habit',
      'Name something people are afraid of',
      'Name something that makes you smile',
      'Name a superpower you\'d want',
      'Name something you\'d find on a deserted island',
      'Name something you\'d save in a fire',
      'Name a childhood toy',
      'Name something that reminds you of summer',
      'Name something that reminds you of winter',
      'Name something that everyone owns',
      'Name something that always runs out too quickly',
      'Name something that never goes out of style',
      'Name a sign that someone is tired',
      'Name something that was better when you were a kid',
      'Name something you\'d put in a time capsule',
      'Name a thing that people lie about',
      'Name a sign that you\'re getting old',
      'Name a way to waste time',
      'Name something that always takes longer than expected',
      'Name something people say at a party',
      'Name a thing you only do when no one is watching',
      'Name something you regret buying',
      'Name a first-world problem',
      'Name something that always happens at the worst time',
      'Name something satisfying to do',
      'Name something that costs way too much',
      'Name something fun to do in the rain',
      'Name a thing that makes you feel nostalgic',
      'Name something you\'d do with a million pounds',
      'Name a rule you always break',
      'Name something a grandparent might say',
      'Name a classic children\'s TV show',
      'Name a thing adults pretend to enjoy',
      'Name something you say you\'ll do but never do',
      'Name a thing everyone secretly loves',
      'Name something satisfying to pop or squeeze',
      'Name a thing you\'d do on a lazy day',
      'Name something you\'d wish for from a genie',
    ],
  },
];

// Build a flat "all" prompts array from every category prompt list.
const ALL_PROMPTS = CATEGORIES.filter(c => c.id !== 'all').flatMap(c => c.prompts);

/**
 * Returns the valid category ids (including 'all').
 */
const VALID_CATEGORY_IDS = CATEGORIES.map(c => c.id);

/**
 * Returns a random prompt from the given category id.
 * Falls back to picking from all prompts if the id is unknown or 'all'.
 */
function pickPrompt(categoryId) {
  const category = CATEGORIES.find(c => c.id === categoryId && c.id !== 'all');
  const pool = category ? category.prompts : ALL_PROMPTS;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { CATEGORIES, VALID_CATEGORY_IDS, pickPrompt };
